<?php
/**
Author: Virat Gaywala
created on : 12-JAN-2016
Purpose:to define tables which are used in MCA
Last modified : Virat Gaywala
Last modified On : 12-JAN-2016
*/

define('TABLE_USER_MASTER','USER_MST');
define('TABLE_CITY_MASTER','CITY_MST');
define('TABLE_STATE_MASTER','STATE_MST');
define('TABLE_PRODUCT_MASTER','PRODUCT_MST');
define('TABLE_USER_PRODUCT_DETAIL','USER_PRODUCT_DTL');
define('TABLE_PRODUCT_PRICE_DETAIL','PRODUCT_PRICE_DTL');
define('TABLE_ORDER_DETAIL','ORDER_DTL');
define('TABLE_QUOTE_DETAIL','QUOTE_DTL');
define('TABLE_INVOICE_DETAIL','INVOICE_DTL');
define('TABLE_COMPANY_MASTER','COMPANY_MST');
define('TABLE_USER_COMPANY_DETAIL','USER_COMPANY_DTL');
define('TABLE_KEY_DETAIL','KEY_DTL');
define('TABLE_INQUIRY_DETAIL','INQUIRY_DTL');
define('TABLE_INSTANCE_DOC_DETAIL','INSTANCE_DOC_DTL');
define('TABLE_XBRL_NEWS_MASTER','XBRL_NEWS_MST');
define('TABLE_NEWSLETTER_XBRL_EDGE','NEWSLETTER_XBRL_EDGE');
define('TABLE_USER_VISIT','USER_VISITED');
define('TABLE_USER_UPLOAD_DOC','USER_DOC_PLOT');
?>